// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
  var myConf;
  require('load-grunt-tasks')(grunt);
  require('time-grunt')(grunt);
  myConf = {
    build: 'build',
    version: '0.2.0'
  };
  grunt.initConfig({
    myConf: myConf,
    clean: {
      build: {
        files: [
          {
            src: ['<%= myConf.build %>/**/*']
          }
        ]
      }
    },
    concat: {
      build: {
        options: {
          banner: "/* Oktell-voice.js version <%= myConf.version %> http://js.oktell.ru/js/voice/ */\n\n"
        },
        files: [
          {
            src: ['jssip-0.3.7.js', 'oktell-voice.js'],
            dest: '<%= myConf.build %>/oktell-voice.js'
          }
        ]
      }
    },
    uglify: {
      build: {
        files: {
          '<%= myConf.build %>/oktell-voice.min.js': ['<%= myConf.build %>/oktell-voice.js']
        }
      }
    }
  });
  grunt.registerTask('build', ['concat:build', 'uglify:build']);
  return grunt.registerTask('default', ['build']);
};
