// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice,
    hasProp = {}.hasOwnProperty;

  window.oktellVoice = (function() {
    var JsSIPAccount, debugMode, eventSplitter, events, extend, j, key, len, log, manager, okVoice, ref, userMedia;
    debugMode = false;
    log = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (!debugMode) {
        return;
      }
      args.unshift('Oktell-Voice.js |');
      return console.log.apply(console, args);
    };
    eventSplitter = /\s+/;
    events = {
      on: function(eventNames, callback, context) {
        var callbacks, event, eventCallbacks, j, len;
        if (!eventNames || typeof callback !== 'function') {
          return false;
        }
        eventNames = eventNames.split(eventSplitter);
        callbacks = this.__eventCallbacks || (this.__eventCallbacks = {});
        for (j = 0, len = eventNames.length; j < len; j++) {
          event = eventNames[j];
          eventCallbacks = callbacks[event] || (callbacks[event] = []);
          eventCallbacks.push({
            fn: callback,
            context: context
          });
        }
        return true;
      },
      off: function(eventNames, callback) {
        var callbacks, event, eventCallback, eventCallbacks, i, j, k, l, len, len1, len2;
        if (eventNames == null) {
          this.__eventCallbacks = {};
        } else {
          callbacks = this.__eventCallbacks || (this.__eventCallbacks = {});
          eventNames = eventNames.split(eventSplitter);
          if (callback == null) {
            for (j = 0, len = eventNames.length; j < len; j++) {
              event = eventNames[j];
              delete callbacks[event];
            }
          } else {
            for (k = 0, len1 = eventNames.length; k < len1; k++) {
              event = eventNames[k];
              eventCallbacks = callbacks[event] || (callbacks[event] = []);
              for (i = l = 0, len2 = eventCallbacks.length; l < len2; i = ++l) {
                eventCallback = eventCallbacks[i];
                if (eventCallback.fn === callback) {
                  eventCallbacks[i] = false;
                }
              }
            }
          }
        }
        return true;
      },
      trigger: function() {
        var args, callbacks, event, eventCallbacks, eventInfo, eventNames, j, k, len, len1, results;
        eventNames = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
        if (!eventNames) {
          return false;
        }
        eventNames = eventNames.split(eventSplitter);
        callbacks = this.__eventCallbacks || (this.__eventCallbacks = {});
        results = [];
        for (j = 0, len = eventNames.length; j < len; j++) {
          event = eventNames[j];
          eventCallbacks = callbacks[event] || (callbacks[event] = []);
          for (k = 0, len1 = eventCallbacks.length; k < len1; k++) {
            eventInfo = eventCallbacks[k];
            if (eventInfo.fn != null) {
              eventInfo.fn.apply(eventInfo.context || window, args);
            }
          }
          args.unshift(event);
          results.push((function() {
            var l, len2, ref, results1;
            ref = callbacks['all'] || [];
            results1 = [];
            for (l = 0, len2 = ref.length; l < len2; l++) {
              eventInfo = ref[l];
              if (eventInfo.fn != null) {
                results1.push(eventInfo.fn.apply(eventInfo.context || window, args));
              } else {
                results1.push(void 0);
              }
            }
            return results1;
          })());
        }
        return results;
      }
    };
    extend = function() {
      var args, i, j, key, ref, ref1, target, val;
      target = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (i = j = ref = args.length - 1; ref <= 0 ? j <= 0 : j >= 0; i = ref <= 0 ? ++j : --j) {
        if (typeof args[i] === 'object') {
          ref1 = args[i];
          for (key in ref1) {
            if (!hasProp.call(ref1, key)) continue;
            val = ref1[key];
            target[key] = val;
          }
        }
      }
      return target;
    };
    userMedia = false;
    okVoice = {
      isOktellVoice: true,
      getUserMediaStream: function() {
        return userMedia;
      },
      isSupported: function() {
        var isChrome, isFirefox, isOpera, isYaBrowser, ref, ref1;
        isChrome = Boolean(navigator.userAgent.match(/Chrome\/[0-9\.]+? Safari\/[0-9\.]+$/));
        isYaBrowser = parseInt((ref = navigator.userAgent.match(/Chrome\/[0-9\.]+? YaBrowser\/([0-9]+)/)) != null ? ref[1] : void 0) >= 14;
        isOpera = parseInt((ref1 = navigator.userAgent.match(/Chrome\/[0-9\.]+? Safari\/[0-9\.]+ OPR\/([0-9]+)/)) != null ? ref1[1] : void 0) >= 20;
        isFirefox = Boolean(navigator.userAgent.match(/Firefox\/[0-9\.]+/));
        return isChrome || isYaBrowser || isOpera || isFirefox;
      }
    };
    extend(okVoice, events);
    JsSIPAccount = (function() {
      JsSIPAccount.prototype.sip = window.JsSIP;

      function JsSIPAccount(login, pass, server, useWSS) {
        this.id = '';
        this.connected = false;
        this.login = login;
        this.pass = pass || '';
        this.server = server != null ? server.split(':')[0] : void 0;
        this.port = (server != null ? server.split(':')[1] : void 0) || '5060';
        this.useWSS = useWSS;
        this.name = 'JsSIP account';
        this.currentSession = false;
        this.connectedFired = false;
        if (this.sip && this.login && this.server && this.port) {
          this.constructed = true;
        }
        this.on('all', (function(_this) {
          return function() {
            var args, event;
            event = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
            return log('EVENT ' + event + ' on ' + _this.getName(), args);
          };
        })(this));
      }

      JsSIPAccount.prototype.getName = function() {
        return this.name + ' #' + this.id;
      };

      JsSIPAccount.prototype.isConnected = function() {
        return this.connected;
      };

      JsSIPAccount.prototype.createFantomAbonent = function(newSession) {
        var abonents, caller;
        caller = typeof newSession === 'string' || typeof newSession === 'number' ? newSession : newSession.getRemoteFriendlyName();
        abonents = [
          {
            phone: caller.toString(),
            name: caller.toString()
          }
        ];
        return abonents;
      };

      JsSIPAccount.prototype.createAudioElements = function() {
        this.elLocal = document.createElement('audio');
        this.elRemote = document.createElement('audio');
        this.elLocalId = 'oktellVoice_jssip_local_' + Date.now();
        this.elRemoteId = 'oktellVoice_jssip_remote_' + Date.now();
        this.elLocal.setAttribute('id', this.elLocalId);
        this.elRemote.setAttribute('id', this.elRemoteId);
        document.body.appendChild(this.elLocal);
        return document.body.appendChild(this.elRemote);
      };

      JsSIPAccount.prototype.connect = function() {
        var config;
        if (!this.constructed) {
          log.error('error while construct ' + this.getName());
          return false;
        }
        log(this.getName() + ' connect', arguments);
        if (!this.elLocal) {
          this.createAudioElements();
        }
        config = {
          ws_servers: (this.useWSS ? 'wss' : 'ws') + '://' + this.server + ':' + this.port,
          uri: 'sip:' + this.login + '@' + this.server,
          password: this.pass,
          via_host: this.server
        };
        if (debugMode) {
          JsSIP.debug.enable('JsSIP:*');
        } else {
          JsSIP.debug.disable('JsSIP:*');
        }
        this.UA = new this.sip.UA(config);
        if (debugMode) {
          window.sipua = this.UA;
        }
        this.UA.on('connected', (function(_this) {
          return function(e) {
            log('connected', e);
            _this.connected = true;
            if (!_this.connectedFired) {
              _this.connectedFired = true;
              return _this.trigger('connect');
            }
          };
        })(this));
        this.UA.on('disconnected', (function(_this) {
          return function(e) {
            _this.connectedFired = false;
            return log('disconnected', e);
          };
        })(this));
        this.UA.on('registered', (function(_this) {
          return function(e) {
            log('registered', e);
            _this.connected = true;
            if (!_this.connectedFired) {
              _this.connectedFired = true;
              return _this.trigger('connect');
            }
          };
        })(this));
        this.UA.on('unregistered', (function(_this) {
          return function(e) {
            log('unregistered', e);
            _this.connected = false;
            _this.UA.stop();
            return _this.trigger('disconnect');
          };
        })(this));
        this.UA.on('registrationFailed', (function(_this) {
          return function(e) {
            log('registration failed', e);
            _this.connected = false;
            _this.UA.stop();
            return _this.trigger('disconnect');
          };
        })(this));
        this.UA.on('mediaPermissionsRequest', (function(_this) {
          return function(e) {
            log('media permissions request', e);
            return _this.trigger('mediaPermissionsRequest');
          };
        })(this));
        this.UA.on('mediaPermissionsAccept', (function(_this) {
          return function(e) {
            log('media permissions accept', e);
            return _this.trigger('mediaPermissionsAccept');
          };
        })(this));
        this.UA.on('mediaPermissionsRefuse', (function(_this) {
          return function(e) {
            log('media permissions refuse', e);
            return _this.trigger('mediaPermissionsRefuse');
          };
        })(this));
        this.UA.on('newRTCSession', (function(_this) {
          return function(e) {
            var onSessionStart;
            log('new RTC session', e);
            _this.currentSession = e.data.session;
            onSessionStart = function(e) {
              var ref, ref1, ref2, ref3, ref4, ref5;
              log('currentSession started', e);
              _this.trigger('RTCSessionStarted', (ref = _this.currentSession.remote_identity) != null ? ref.display_name : void 0);
              if (((ref1 = _this.currentSession) != null ? ref1.direction : void 0) === 'incoming') {
                _this.trigger('ringStart', (ref2 = _this.currentSession) != null ? (ref3 = ref2.remote_identity) != null ? ref3.display_name : void 0 : void 0, (ref4 = _this.currentSession) != null ? (ref5 = ref4.remote_identity) != null ? typeof ref5.toString === "function" ? ref5.toString() : void 0 : void 0 : void 0);
              }
              if (_this.currentSession.getLocalStreams().length > 0) {
                log('currentSession local stream > 0', _this.currentSession.getRemoteStreams()[0].getAudioTracks());
                _this.elLocal.src = window.URL.createObjectURL(_this.currentSession.getLocalStreams()[0]);
              } else {
                log('currentSession local stream == 0');
              }
              if (_this.currentSession.getRemoteStreams().length > 0) {
                log('currentSession remote stream > 0', _this.currentSession.getRemoteStreams()[0].getAudioTracks());
                _this.elRemote.src = window.URL.createObjectURL(_this.currentSession.getRemoteStreams()[0]);
                return _this.elRemote.play();
              } else {
                return log('currentSession remote stream == 0');
              }
            };
            if (_this.currentSession.direction === 'incoming') {
              onSessionStart();
            } else {
              _this.currentSession.on('confirmed', onSessionStart);
            }
            _this.currentSession.on('progress', function(e) {
              return log('currentSession progress', e);
            });
            _this.currentSession.on('failed', function(e) {
              var ref;
              log('currentSession failed', e);
              return _this.trigger('RTCSessionFailed', (ref = _this.currentSession.remote_identity) != null ? ref.display_name : void 0);
            });
            _this.currentSession.on('ended', function(e) {
              var ref;
              log('currentSession ended');
              return _this.trigger('RTCSessionEnded', (ref = _this.currentSession.remote_identity) != null ? ref.display_name : void 0);
            });
            return _this.currentSession.on('hold', function(e) {
              return _this.holdedSession = _this.currentSession;
            });
          };
        })(this));
        return this.UA.start();
      };

      JsSIPAccount.prototype.call = function(number) {
        var options;
        if (!number || !this.connected) {
          return false;
        }
        log(this.getName() + ' call', arguments);
        number = number.toString();
        options = {
          mediaConstraints: {
            'audio': true,
            'video': false
          }
        };
        return this.UA.call(number, options);
      };

      JsSIPAccount.prototype.answer = function() {
        var ref;
        return (ref = this.currentSession) != null ? typeof ref.answer === "function" ? ref.answer({
          'audio': true,
          'video': false
        }) : void 0 : void 0;
      };

      JsSIPAccount.prototype.hangup = function() {
        var ref;
        return (ref = this.currentSession) != null ? typeof ref.terminate === "function" ? ref.terminate() : void 0 : void 0;
      };

      JsSIPAccount.prototype.reject = function() {
        var ref;
        return (ref = this.currentSession) != null ? typeof ref.terminate === "function" ? ref.terminate() : void 0 : void 0;
      };

      JsSIPAccount.prototype.hold = function() {
        var ref;
        return (ref = this.currentSession) != null ? typeof ref.hold === "function" ? ref.hold() : void 0 : void 0;
      };

      JsSIPAccount.prototype.isOnHold = function() {
        var ref;
        return (ref = this.holdedSession) != null ? typeof ref.isOnHold === "function" ? ref.isOnHold() : void 0 : void 0;
      };

      JsSIPAccount.prototype.resume = function() {
        var ref;
        return (ref = this.holdedSession) != null ? typeof ref.unhold === "function" ? ref.unhold() : void 0 : void 0;
      };

      JsSIPAccount.prototype.dtmf = function(digit) {
        var ref;
        return (ref = this.currentSession) != null ? typeof ref.sendDTMF === "function" ? ref.sendDTMF(digit) : void 0 : void 0;
      };

      JsSIPAccount.prototype.transfer = function(to) {
        var ref;
        if (!to) {
          return false;
        }
        return (ref = this.currentSession) != null ? typeof ref.transfer === "function" ? ref.transfer(to.toString()) : void 0 : void 0;
      };

      JsSIPAccount.prototype.disconnect = function() {
        return this.UA.stop();
      };

      return JsSIPAccount;

    })();
    extend(JsSIPAccount.prototype, events);
    okVoice.createUserMedia = (function(_this) {
      return function(onSuccess, onDeny, useVideo, audioOptions) {
        var defaultAudioOptions, getUserMedia, hasDecision, triggerDeny;
        if (audioOptions == null) {
          audioOptions = {};
        }
        if (userMedia) {
          return typeof onSuccess === "function" ? onSuccess(userMedia) : void 0;
        }
        hasDecision = false;
        triggerDeny = function(st) {
          hasDecision = true;
          okVoice.trigger('mediaPermissionsRefuse');
          return typeof onDeny === "function" ? onDeny(st) : void 0;
        };
        getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
        defaultAudioOptions = {
          mandatory: {
            googAutoGainControl: false
          },
          optional: []
        };
        if (!okVoice.isSupported() || typeof getUserMedia !== 'function') {
          triggerDeny();
          return false;
        }
        setTimeout(function() {
          if (!hasDecision) {
            return okVoice.trigger('mediaPermissionsRequest');
          }
        }, 500);
        return getUserMedia.call(navigator, {
          audio: extend({}, defaultAudioOptions, audioOptions),
          video: useVideo
        }, function(st) {
          hasDecision = true;
          userMedia = st;
          okVoice.trigger('mediaPermissionsAccept');
          return typeof onSuccess === "function" ? onSuccess(userMedia) : void 0;
        }, function(error) {
          return triggerDeny(error);
        });
      };
    })(this);
    manager = {
      accCount: 0,
      currentAcc: null,
      defaultOptions: {
        debugMode: false
      },
      exportFnNames: ['call', 'answer', 'hangup', 'transfer', 'hold', 'isOnHold', 'resume', 'dtmf', 'reject', 'isConnected'],
      createExportAccount: function(account) {
        var a, j, key, len, ref;
        if (account == null) {
          return false;
        }
        a = {};
        ref = this.exportFnNames;
        for (j = 0, len = ref.length; j < len; j++) {
          key = ref[j];
          if (account[key] != null) {
            (function() {
              var val;
              val = account[key];
              return a[key] = function() {
                return val.apply(account, arguments);
              };
            })();
          }
        }
        extend(a, events);
        account.on('all', (function(_this) {
          return function() {
            var args;
            args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
            return a.trigger.apply(a, args);
          };
        })(this));
        return a;
      },
      createAccount: function(opts) {
        var acc;
        opts = extend({}, opts || {}, this.defaultOptions);
        debugMode = Boolean(opts.debugMode);
        acc = new JsSIPAccount(opts.login, opts.password, opts.server, opts.useWSS);
        acc.id = ++this.accCount;
        acc.connect();
        return acc;
      },
      disposeCurrentAcc: function() {
        var ref;
        if ((ref = this.currentAcc) != null) {
          if (typeof ref.disconnect === "function") {
            ref.disconnect();
          }
        }
        return this.currentAcc = null;
      }
    };
    ref = manager.exportFnNames;
    for (j = 0, len = ref.length; j < len; j++) {
      key = ref[j];
      okVoice[key] = function() {
        return false;
      };
    }
    okVoice.disconnect = (function(_this) {
      return function() {
        return manager.disposeCurrentAcc();
      };
    })(this);
    okVoice.connect = function(options) {
      var exportAcc;
      manager.disposeCurrentAcc();
      manager.currentAcc = manager.createAccount(options);
      exportAcc = manager.createExportAccount(manager.currentAcc);
      extend(okVoice, exportAcc);
      exportAcc.on('all', (function(_this) {
        return function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return okVoice.trigger.apply(okVoice, args);
        };
      })(this));
      exportAcc.disconnect = function() {
        return okVoice.disconnect();
      };
      return exportAcc;
    };
    okVoice.version = '0.2.4';
    return okVoice;
  })();

}).call(this);
